# Generated by Django 4.2.5 on 2023-09-27 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUsModel',
        ),
    ]
