# Generated by Django 4.2.5 on 2023-09-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact_module', '0002_delete_contactusmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('email', models.EmailField(max_length=200, verbose_name='ایمیل')),
                ('full_name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('is_read_by_admin', models.BooleanField(default=True, verbose_name='خوانده شده توسط ادمین')),
                ('response', models.TextField(verbose_name='پاسخ ادمین')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد پیام')),
            ],
            options={
                'verbose_name': 'تماس با ما',
                'verbose_name_plural': 'لیست تماس با ما',
            },
        ),
    ]
