# Generated by Django 4.2.5 on 2023-10-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0002_articlecategory_parent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=100, verbose_name='لینک')),
                ('image', models.ImageField(upload_to='article', verbose_name='تصویر مقاله')),
                ('text', models.TextField(verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال / غیر فعال')),
                ('selected_category', models.ManyToManyField(to='article_module.articlecategory', verbose_name='دسته بندی مقالات')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
    ]
