# Generated by Django 4.2.5 on 2023-10-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0005_article_create_date_alter_article_auther'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='برچسب مقاله'),
        ),
    ]
