# Generated by Django 4.2.5 on 2023-09-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100, verbose_name='نام سایت')),
                ('site_url', models.CharField(max_length=100, verbose_name='دامنه سایت')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='تلفن')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='آدرس')),
                ('email', models.CharField(max_length=25, verbose_name='ایمیل')),
                ('fax', models.CharField(blank=True, max_length=12, null=True, verbose_name='فکس')),
                ('logo', models.ImageField(upload_to='images/sire_setting/', verbose_name='تصویر لوگو')),
                ('copy_right', models.TextField(verbose_name='متن کپی رایت')),
                ('about_us', models.TextField(verbose_name='درباره ما')),
                ('is_mean_site', models.BooleanField(default=False, verbose_name='تنظیمات اضلی')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات',
            },
        ),
    ]
