# Generated by Django 4.2.5 on 2023-09-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0003_footerlinkbox_alter_sitesetting_fax_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('link_title', models.CharField(max_length=100, verbose_name='عنوان لینک')),
                ('link', models.CharField(max_length=100, verbose_name='لینک')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='images/slider', verbose_name='تصویر  اسلایدر')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'تنظیمات اسلایدر',
            },
        ),
    ]
