# Generated by Django 4.2.5 on 2023-10-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0006_alter_slider_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('url', models.URLField(blank=True, max_length=300, null=True, verbose_name='لینک')),
                ('image', models.ImageField(upload_to='images/banner', verbose_name='تصویر بنر')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال / غیر فعال')),
                ('position', models.CharField(max_length=250, verbose_name='جایگاه نمایش')),
            ],
            options={
                'verbose_name': 'بنر تبلیغات',
                'verbose_name_plural': 'بنر های تبلیغاتی',
            },
        ),
    ]
